import Head from "next/head";
import { getSession } from "next-auth/client";
import Header from "../components/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Posts from "../components/Posts";
import Widgets from "../components/Widgets";
import { db } from "../firebase";

export default function Home({ session , posts}) {
  if (!session) {
    return <Login />;
  }
  return (
    <div className="bg-gray-100">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/social.webp" />
      </Head>

      <Header />

      <main className="flex ">
        <Sidebar />
        <Feed posts={posts} />
        <Widgets />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

  const docs = posts.docs.map(post => ({
    id:post.id,
    ...post.data(),
    timestamp:null,
  }))

  return {
    props: {
      session,
      posts:docs,
    },
  };
}
